
# This folder builds JSSS and Ring2025

apply:
	terraform apply -auto-approve

init:
	terraform init -upgrade

login:
# l'unico account che updata DNS..
	gcloud auth login palladiusbonton@gmail.com --update-adc
